name: Zig Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    
    - name: Build and Test
      run: |
        zig build test
      
    - name: Run Benchmarks
      run: |
        zig build bench

  docs:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    
    - name: Setup Cache Directories
      run: |
        mkdir -p ~/.cache/zig
        sudo chown -R $(id -u):$(id -g) ~/.cache/zig
        sudo chmod -R 755 ~/.cache/zig
        
    - name: Generate Documentation
      run: |
        echo "Starting documentation generation..."
        mkdir -p docs
        zig test -femit-docs src/root.zig --dep std
        mv *.html docs/ 2>/dev/null || echo "No HTML files to move"
        
        echo "Documentation files:"
        ls -la docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
        commit_message: "docs: update documentation [skip ci]"