name: Zig Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    
    - name: Build and Test
      run: |
        zig build test
      
    - name: Run Benchmarks
      run: |
        zig build bench

  docs:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    
    - name: Setup Zig cache directory
      run: |
        mkdir -p ~/.cache/zig
        chmod 777 ~/.cache/zig
    
    - name: Generate Documentation
      run: |
        zig build docs
        ls -la  # List all files
        find . -name "*.html"  # Find any HTML files

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Change this to root directory since docs are generated here
        force_orphan: true
        commit_message: "docs: update documentation"