name: Zig Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    
    - name: Build and Test
      run: |
        zig build test
      
    - name: Run Benchmarks
      run: |
        zig build bench

  docs:
    needs: test  # Only build docs after tests pass
    if: github.ref == 'refs/heads/main'  # Only deploy docs from main branch
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing to gh-pages branch
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
    
    - name: Generate Documentation
      run: |
        zig build docs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true  # Keep gh-pages branch clean
        commit_message: "docs: update documentation"